### ISSUE TITLE
Class-Diagram

### ISSUE THREAD

**Issue by m-pauly** [m-pauly/sensorik-lidar#25]
![Class Diagram1](https://user-images.githubusercontent.com/63288980/140648096-c9130229-cd68-4842-96b5-8033bbbea8d0.png)

**Comment by MoBarside** [comment]
Functions for visualization added
Todo: add missing functions 

![13B35CA8-522F-4BBD-977F-CAD4E50622FC](https://user-images.githubusercontent.com/73947013/142020578-5f0a28c2-b2ca-42f9-bcc5-64694cd23117.jpeg)
