### ISSUE TITLE
Sequence-Diagram

### ISSUE THREAD

**Issue by m-pauly** [m-pauly/sensorik-lidar#26]
![36D2C325-9F08-42F2-84E7-6B635AE3B3F9](https://user-images.githubusercontent.com/73947013/142016288-d5192d84-2485-4372-a4da-415075a207ff.jpeg)

**Comment by MoBarside** [comment]
![Uploading C79461B3-D51D-405C-85FC-AA1428F71543.jpeg…]()

**Comment by MoBarside** [comment]
![E0868086-D27A-47D9-AB11-BF52C06C7191](https://user-images.githubusercontent.com/73947013/141941432-140e8f63-97d3-4104-a07e-ba42340901b0.jpeg)
